CREATE TABLE presensi (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nama TEXT NOT NULL,
    asal VARCHAR(255) NOT NULL,
    ucapan TEXT,
    ip_address VARCHAR(45) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
